version: "3.8"

services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    container_name: mongodb
#
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: max
#    - MONGO_INITDB_ROOT_USERNAME=max
    env_file:
      - ./env/mongo.env

  backend:
#     relative path to Dockerfile
#    build: ./backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
#      - ./backend:/app //doesn't work on windows
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  fontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: